# -*- coding: utf-8 -*-
"""PBO-Type data SET

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fNfXwf-S0S7_A_JdAhO-pClGZYv8Pv1T

NAMA : RIVALDI KENNY N

KELAS : PBO Praktik 7

                      TYPE DATA SET

**MENAMBAHKAN DATA**
"""

# ADD()

tes = {'rivaldi','kenny','nugraha'}
print(tes)

tes.add('kelas')
tes.add('INFORMATIKA E')

print(tes)

# UPDATE()

tes = {'rivaldi','kenny','nugraha'}
print(tes)

tes.update({'kelas','INFORMATIKA E'})
tes.update({'ANGKATAN',2021})

print(tes)

"""**Menghapus Data**"""

# remove()

tes = {'rivaldi','kenny','nugraha','INFORMATIKA E',5210411240}
tes.remove(5210411240)
print(tes)

# discard()

tes = {'rivaldi','kenny','nugraha','INFORMATIKA E',5210411240}
tes.discard('kenny')
print(tes)

# pop()

tes = {'rivaldi','kenny','nugraha','INFORMATIKA E',5210411240}
YangDihapus = tes.pop()
print('YangDihapus =', YangDihapus)
print(tes)

# clear()

tes = {'rivaldi','kenny','nugraha','INFORMATIKA E',5210411240}
tes.clear()
print(tes)

"""**Fungsi Union**"""

tes1 = {
    'a','b','c'
}

tes2 = {
    'Rivaldi Kenny N','d','e'
}

# cara1
print(tes1 | tes2)
# cara2
print(tes1.union(tes2))

"""**Fungsi Intersection (Irisan)**"""

tes1 = {
    'a','b','c','d','e'
}

tes2 = {
    'd','Rivaldi Kenny N','b','e'
}
#cara1
print(tes1 & tes2)
 # cara 2
print(tes1.intersection(tes2))

"""**Fungsi Difference (Selisih)**"""

tes1 = {
    'a','b','c'
}

tes2 = {
    'Rivaldi Kenny N','b','e'
}

print(' Yang bukan anggota tes2 :')
print(tes1 - tes2)
print(tes1.difference(tes2))

print(' Yang bukan anggota tes1 :')
print(tes2 - tes1)
print(tes2.difference(tes1))

"""**Symmetric Difference (Yang hanya menjadi anggota satu grup saja)**"""

tes1 = {
    'a','b','c'
}

tes2 = {
    'Rivaldi Kenny N','b','e'
}

print(' Yang bukan anggota tes2 :')
print(tes1 - tes2)
print(tes1.difference(tes2))
print('\t')
print(' Yang bukan anggota tes1 :')
print(tes2 - tes1)
print(tes2.difference(tes1))

# symmetric_difference
print('\nanggota yang hanya ikut satu anggota saja:')
print(tes2.symmetric_difference(tes1))